#!/usr/bin/env bash

OUTPUT=${1:-bin/stssvc}
echo "Building sts ..."
mkdir -p bin
if command -v dep >/dev/null 2>&1; then 
  echo 'exists dep' 
else 
  echo 'no exists dep' 
  curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
fi
dep ensure -v

go build -o $OUTPUT cmd/stssvc.go
